The run id is 3555hs7x
Epoch: 1 / 30:   0%|                                                                                                                                         | 0/964 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 504, in <module>
    main(args)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 445, in main
    train(args, model, train_loader, test_loader, device, restart = args.restart)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 258, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 193, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 212, in parallel_apply
    return parallel_apply(
           ^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 126, in parallel_apply
    output.reraise()
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
torch.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 96, in _worker
    output = module(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/Sami_DLV3+_Brickfield/DeepLabV3Plus/network/utils.py", line 16, in forward
    x = self.classifier(features)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/Sami_DLV3+_Brickfield/DeepLabV3Plus/network/_deeplab.py", line 49, in forward
    output_feature = self.aspp(feature['out'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/Sami_DLV3+_Brickfield/DeepLabV3Plus/network/_deeplab.py", line 160, in forward
    res.append(conv(x))
               ^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/modules/batchnorm.py", line 193, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/nn/functional.py", line 2822, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 56.00 MiB. GPU 0 has a total capacity of 47.71 GiB of which 93.25 MiB is free. Process 2858169 has 16.29 GiB memory in use. Including non-PyTorch memory, this process has 25.52 GiB memory in use. Of the allocated memory 24.78 GiB is allocated by PyTorch, and 148.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
